version: "3"

server:
  command: "php bin/roadrunner"
  relay: pipes

rpc:
  listen: tcp://0.0.0.0:6001

jobs:
  num_pollers: 16
  timeout: 60
  pipeline_size: 100000
  pool:
    num_workers: 8
    allocate_timeout: 60s
    destroy_timeout: 60s
  consume: ["default"]
  pipelines:
    default:
      driver: memory
      config:
        priority: 10
        prefetch: 100

reload:
  # sync interval
  interval: 1s
  # global patterns to sync
  patterns: [".php"]
  # list of included for sync services
  services:
    http:
      # recursive search for file patterns to add
      recursive: true
      # ignored folders
      ignore:
        [
          "vendor/",
          "resources/cache/",
          "resources/docs",
          ".devspace",
          ".vscode/",
          ".idea/",
        ]
      # service specific file pattens to sync
      patterns: [".php"]
      # directories to sync. If recursive is set to true,
      # recursive sync will be applied only to the directories in `dirs` section
      dirs: ["."]

endure:
  # default 30s to finish, possible values 10s,100m,5h
  grace_period: 30s
  # default false, print graph in the graphviz format to the stdout (paste here to visualize https://dreampuf.github.io)
  print_graph: false
  # default error, possible values: debug, info, warning, error, panic, fatal
  log_level: error
